version: '3'

services:
    nginx:
        image: nginx:1.15-alpine
        depends_on:
            - flask_app
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./data/nginx:/etc/nginx/conf.d
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
    certbot:
        image: certbot/certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
    flask_app:
        image: flask_app        
        build:
            context: .
            dockerfile: ./Dockerfile
        environment: 
            - SECRET_KEY=20913b25e91768f01b7ad93766783c8b
            - SQLALCHEMY_DATABASE_URI=sqlite:///isaqwebsite.db
