version: '3'

services:

    flask_app:
        container_name: flask_app
        restart: always
        build: ./flask_app
        environment: 
            - SECRET_KEY=20913b25e91768f01b7ad93766783c8b
            - SQLALCHEMY_DATABASE_URI=sqlite:///isaqwebsite.db
        volumes:
            - static_volume:/home/isaq/flask_app/ISAQ/static
        ports:
            - "8000:8000"
        command: gunicorn -w 1 -b 0.0.0.0:8000 app:app
        networks:
            - my-network    
    nginx:
        container_name: nginx
        build: ./nginx
        volumes:
            - static_volume:/home/isaq/flask_app/ISAQ/static
            - ./nginx:/etc/nginx/conf.d
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - flask_app
        networks:
            - my-network
    certbot:
        image: certbot/certbot
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes: 
    static_volume:

networks: 
    my-network: