echo Installing ufw...
apt install ufw

echo Installing make...
apt install make

echo Configuring firewall outgoing rule...
ufw default allow outgoing

echo Configuring firewall incoming rule...
ufw default deny incoming

echo Configuring firewall ssh rule...
ufw allow ssh

echo Configuring firewall http rule...
ufw allow http/tcp

echo Configuring firewall https rule...
ufw allow https

echo Running docker...
make dc-start

echo Enabling firewall...
ufw enable
