echo updating...
apt-get update

echo installing software properties universe common...
apt-get install software-properties-common

echo adding universe repo...
add-apt-repository universe

echo adding certbot repo...
add-apt-repository ppa:certbot/certbot

echo updating...
apt-get update

echo installing certbot for python3 and nginx...
apt-get install certbot python3-certbot-nginx

echo running certbox on nginx...
certbot --nginx

echo testing automatic renewel...
certbot renew --dry-run